- name: set variables depending on installation mode
  tags: always
  include_vars: "{{ openhab_installation_mode }}.yml"

- name: Include tasks depending on installation mode
  tags: install
  include: "install-{{ openhab_installation_mode }}.yml"

- name: Add Azul repo key
  when: openhabian_install_java | bool
  become: True
  apt_key:
    id: "0xB1998361219BD9C9"
    keyserver: keyserver.ubuntu.com
- name: Add Azul repository
  when: openhabian_install_java | bool
  become: True
  apt_repository:
    repo: deb http://repos.azulsystems.com/ubuntu stable main
    state: present
- name: install java environment
  when: openhabian_install_java | bool
  become: True
  apt:
    update_cache: yes
    name:
    - "{{ openhab_java_version }}"

- name: adding '{{ openhabian_user }}' to groups for access to gpios and other hardware
  tags: groups
  become: True
  user:
    name: '{{ openhabian_user }}'
    append: yes
    groups: "{{ openhab_additional_groups }}"

- name: configure http ports
  become: true
  when: openhabian_port_http != openhabian_default_port_http or openhabian_port_https != openhabian_default_port_https
  with_items:
  - { property: 'OPENHAB_HTTP_PORT', value: "{{ openhabian_port_http }}" }
  - { property: 'OPENHAB_HTTPS_PORT', value: "{{ openhabian_port_https }}" }
  lineinfile:
    dest: "{{ openhab_path_environment }}"
    regexp: "{{ item.property | regex_escape() }}"
    line: "{{ item.property }}={{ item.value }}"
    backrefs: yes # to only change if regexp matches
  notify:
  - Reload systemd daemon
  - Restart openhab

- name: delete old key for openhab karaf console login
  when: openhabian_refresh_consoleloginkey
  with_items:
  - "{{ openhabian_consoleloginkey }}"
  - "{{ openhabian_consoleloginkey }}.pub"
  file:
    path: "{{ item }}"
    state: absent
- name: generate key for openhab karaf console login
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_file: "{{ openhabian_consoleloginkey }}"
    ssh_key_comment: ""
  register: userresults
- name: set permissions for openhab config dirs
  become: true
  with_items:
  - "{{ openhab_path_conf }}/"
  - "{{ openhab_path_userdata }}/etc/"
  - "{{ openhab_path_addons }}"
  file:
    path: "{{ item }}"
    owner: "{{ openhabian_user }}"
    group: "{{ openhabian_admin_group }}"
    mode: "{{ openhab_file_permissions }}"
    recurse: yes
- name: add public key to console config
  # see https://community.openhab.org/t/security-of-karaf-console/17661/9
  lineinfile:
    dest: "{{ openhab_path_userdata }}/etc/keys.properties"
    line: "openhab={{ userresults.ssh_public_key[8:] | trim }},_g_:admingroup"
    insertbefore: '^_g_\\:admingroup = group,admin,manager,viewer,systembundles$'
    regexp: 'openhab\='


- name: Configure settings in .cfg files
  with_items:
  - { file: '{{ openhab_path_conf }}/services/addons.cfg', property: 'package', value: "{{ openhabian_addons_package }}" }
  - { file: '{{ openhab_path_conf }}/services/addons.cfg', property: 'binding', value: "{{ openhabian_addons_binding | join(',') }}" }
  - { file: '{{ openhab_path_conf }}/services/addons.cfg', property: 'ui', value: "{{ openhabian_addons_ui | join(',') }}" }
  - { file: '{{ openhab_path_conf }}/services/addons.cfg', property: 'persistence', value: "{{ openhabian_addons_persistence | join(',') }}" }
  - { file: '{{ openhab_path_conf }}/services/addons.cfg', property: 'action', value: "{{ openhabian_addons_action | join(',') }}" }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:language', value: 'de' }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:region', value: 'DE' }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.persistence:default', value: 'mapdb' }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.inbox:autoApprove', value: "{{ openhab_auto_approve }}" }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.links:autoLinks', value: "{{ openhab_auto_link }}" }
  - { file: '{{ openhab_path_userdata }}/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.out.policies.size.size', value: '100MB' }
  - { file: '{{ openhab_path_userdata }}/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.event.policies.size.size', value: '100MB' }
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.property | regex_escape() }}"
    line: "{{ item.property }} = {{ item.value }}"
    backrefs: yes # to only change if regexp matches

- name: Configure some additional settings in .cfg files
  when: openhabian_port_ssh is defined and openhabian_port_lsp is defined
  with_items:
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.apache.karaf.shell:sshPort', value: "{{ openhabian_port_ssh }}" }
  - { file: '{{ openhab_path_conf }}/services/runtime.cfg', property: 'org.eclipse.smarthome.lsp:port', value: "{{ openhabian_port_lsp }}" }
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.property | regex_escape() }}"
    line: "{{ item.property }} = {{ item.value }}"
#    backrefs: yes # to only change if regexp matches

- name: add log level configuration for certain packages
  tags: logging
  blockinfile:
    path: "{{ openhab_path_userdata }}/etc/org.ops4j.pax.logging.cfg"
    insertafter: "log4j2\\.appender\\.osgi\\.filter = \\*"
    block: "{{ openhabian_logging_block }}"
- name: deploy persistence configuration
  with_items: "{{ openhabian_configfiles }}"
  template:
    src: "{{ item.srcpath | default('') }}{{ item.file }}.j2"
    dest: "{{ openhab_path_conf }}/{{ item.folder }}/{{ item.file }}"
    owner: "{{ openhabian_user }}"
    group: "{{ openhabian_admin_group }}"
    mode: "{{ openhab_file_permissions }}"
  become: yes

- name: deploy additional addons from local machine
  tags: addons
  when: openhab_additional_addons_local is defined
  with_items: "{{ openhab_additional_addons_local }}"
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ openhab_path_addons }}/"
    owner: "{{ openhabian_user }}"
    group: "{{ openhabian_admin_group }}"
    mode: "{{ openhab_file_permissions }}"

- name: Deploy additional addons from remote URLs
  tags: addons
  when: openhab_additional_addons_url is defined
  with_items: "{{ openhab_additional_addons_url }}"
  become: true
  get_url:
    url: "{{ item }}"
    dest: "{{ openhab_path_addons }}/"
    owner: "{{ openhabian_user }}"
    group: "{{ openhabian_admin_group }}"
    mode: "{{ openhab_file_permissions }}"

- name: Trigger systemd deamon reload handler
  meta: flush_handlers
- name: Enable and start openHAB
  become: true
  systemd:
    name: "{{ openhab_service_name }}"
    state: started
    enabled: yes

- name: Include InfluxDB installation tasks
  tags: install
  when: openhab_install_influxdb
  include: "influxdb.yml"
