- name: set variables depending on installation mode
  tags: always
  include_vars: "{{openhab_installation_mode}}.yml"

- name: Create user
  when: openhab_installation_mode == "manual"
  user:
    name: "openhab"
    system: yes
    create_home: no
    password_lock: yes

- name: unpack archive
  when: openhab_installation_mode == "manual"
  become: True
  unarchive:
    src: "{{openhab_stable_address}}"
    dest: "{{openhab_path_application}}"
    owner: openhab
    group: openhab
    remote_src: yes

- name: setup openhab as a systemd service
  when: openhab_installation_mode == "manual"
  tags: test
  become: true
  template:
    src: "openhab2.service.j2"
    dest: "/lib/systemd/system/openhab2.service"
#    owner: openhab
#    group: openhab
  notify:
  - Reload systemd daemon
  - Restart openhab

- name: set permissions for openhab config dirs
  become: true
  with_items:
    - "{{openhab_path_conf}}/"
    - "{{openhab_path_userdata}}/etc/"
  file:
    path: "{{item}}"
    owner: openhab
    group: "{{ openhabian_admin_group }}"
    mode: "u+rw,g+rw,o=r"
    recurse: yes

- name: Configure settings in .cfg files
  with_items:
    - { file: '{{openhab_path_conf}}/services/addons.cfg', property: 'package', value: "{{openhabian_addons_package}}" }
    - { file: '{{openhab_path_conf}}/services/addons.cfg', property: 'binding', value: "{{openhabian_addons_binding | join(',')}}" }
    - { file: '{{openhab_path_conf}}/services/addons.cfg', property: 'ui', value: "{{openhabian_addons_ui | join(',')}}" }
    - { file: '{{openhab_path_conf}}/services/addons.cfg', property: 'persistence', value: "{{openhabian_addons_persistence | join(',')}}" }
    - { file: '{{openhab_path_conf}}/services/addons.cfg', property: 'action', value: "{{openhabian_addons_action | join(',')}}" }
    - { file: '{{openhab_path_conf}}/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:language', value: 'de' }
    - { file: '{{openhab_path_conf}}/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:region', value: 'DE' }
    - { file: '{{openhab_path_conf}}/services/runtime.cfg', property: 'org.eclipse.smarthome.persistence:default', value: 'mapdb' }
    - { file: '{{openhab_path_userdata}}/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.out.policies.size.size', value: '100MB' }
    - { file: '{{openhab_path_userdata}}/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.event.policies.size.size', value: '100MB' }
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.property | regex_escape() }}"
    line: "{{ item.property }} = {{ item.value }}"
    backrefs: yes # to only change if regexp matches
- name: add log level configuration for certain packages
  blockinfile:
    path: "{{openhab_path_userdata}}/etc/org.ops4j.pax.logging.cfg"
    insertafter: "log4j2\\.appender\\.osgi\\.filter = \\*"
    block: "{{ openhabian_logging_block }}"
- name: deploy persistence configuration
  with_items: "{{ openhabian_configfiles }}"
  template:
    src: "{{item.srcpath | default('')}}{{item.file}}.j2"
    dest: "{{openhab_path_conf}}/{{item.folder}}/{{item.file}}"
    owner: openhab
    group: "{{ openhabian_admin_group }}"
  become: yes
