- name: set permissions for openhab config dirs
  become: true
  with_items:
    - /etc/openhab2/
    - /var/lib/openhab2/etc/
  file:
    path: "{{item}}"
    owner: openhab
    group: "{{ openhabian_admin_group }}"
    mode: "u+rw,g+rw,o=r"
    recurse: yes

- name: Configure settings in .cfg files
  with_items:
    - { file: '/etc/openhab2/services/addons.cfg', property: 'package', value: "{{openhabian_addons_package}}" }
    - { file: '/etc/openhab2/services/addons.cfg', property: 'binding', value: "{{openhabian_addons_binding | join(',')}}" }
    - { file: '/etc/openhab2/services/addons.cfg', property: 'ui', value: "{{openhabian_addons_ui | join(',')}}" }
    - { file: '/etc/openhab2/services/addons.cfg', property: 'persistence', value: "{{openhabian_addons_persistence | join(',')}}" }
    - { file: '/etc/openhab2/services/addons.cfg', property: 'action', value: "{{openhabian_addons_action | join(',')}}" }
    - { file: '/etc/openhab2/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:language', value: 'de' }
    - { file: '/etc/openhab2/services/runtime.cfg', property: 'org.eclipse.smarthome.core.localeprovider:region', value: 'DE' }
    - { file: '/etc/openhab2/services/runtime.cfg', property: 'org.eclipse.smarthome.persistence:default', value: 'mapdb' }
    - { file: '/var/lib/openhab2/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.out.policies.size.size', value: '100MB' }
    - { file: '/var/lib/openhab2/etc/org.ops4j.pax.logging.cfg', property: 'log4j2.appender.event.policies.size.size', value: '100MB' }
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.property | regex_escape() }}"
    line: "{{ item.property }} = {{ item.value }}"
    backrefs: yes # to only change if regexp matches
- name: add log level configuration for certain packages
  blockinfile:
    path: /var/lib/openhab2/etc/org.ops4j.pax.logging.cfg
    insertafter: "log4j2\\.appender\\.osgi\\.filter = \\*"
    block: "{{ openhabian_logging_block }}"
- name: deploy persistence configuration
  with_items: "{{ openhabian_configfiles }}"
  template:
    src: "{{item.srcpath | default('')}}{{item.file}}.j2"
    dest: "/etc/openhab2/{{item.folder}}/{{item.file}}"
    owner: openhab
    group: "{{ openhabian_admin_group }}"
  become: yes
