- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: yes

- name: Restart openhab
  become: true
  systemd:
    name: "{{ openhab_service_name }}"
    state: restarted

- name: Restart InfluxDB
  become: true
  service:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: True
